### ISSUE TITLE
Myzcloud.me is dead, new site seems to be musify.club

### ISSUE THREAD

**Issue by Pathduck** [Beaglefoot/dl-myzuka.fm#1]
Hello, 
firstly, thank you for the great script, it's been working great for me.

As of a couple of weeks myzcloud seems to be dead (no IP) and I've found that the site `musify.club` is basically the same site. However the download script fails on the site, I've done some debugging found that the `coverURL` var is `undefined`, maybe because they've changed the site code slightly. 

I managed to change the script to work again by either:

1. Removing the `throw error` when downloading the cover image. The script should not fail if the cover is unavailable (IMO).
2. Changing the code to get the coverURL to: `const coverURL = $('.album-img').attr('data-src');` . I don't know why it can no longer find the `src` attribute. 

I made a fork here, maybe you can see if the changes are useful to you?
https://github.com/Pathduck/dl-myzcloud.me

**Comment by Beaglefoot** [comment]
Hi @Pathduck,

I thought they were dead a long time ago. Nice to see that music collection alive.
And thanks for changes, just merged them.
Closed via #2

**Comment by Pathduck** [comment]
Thanks, that's great 😄 👍 

Apologies for keeping the debug lines in there, I didn't get around to removing them 😉
